### PR TITLE
[storescu] prefer file's transfer syntax

### PR DESCRIPTION
**Pull request by PierreBou91**
Hi,

As addressed in #473 , I have slightly adapted the [`check_presentation_context()`](https://github.com/Enet4/dicom-rs/blob/master/storescu/src/main.rs#L563) function to return early if there is an exact match between the file's TS and the TS from the presentation contexts slice that is passed to the function. Otherwise, the previous logic applies. When testing, the selected_ts is consistently the same as the file's TS.

Is it the expected behavior for storescu ?

Additionally, you commented:
> (...)
> The other criterion currently written is to transcode and accept Explicit VR Little Endian otherwise (only when `--never-transcode` is not enabled).
> (...)
_Originally posted by @Enet4 in https://github.com/Enet4/dicom-rs/issues/473#issuecomment-2117643092_

I am uncertain how to address this point and would appreciate some guidance please.

Have a nice day !

### CODE REVIEW

**Comment by Enet4** [comment]
> Is it the expected behavior for storescu ?

That seems to do the trick. :+1:

> Additionally, you commented:
> 
> > (...)
> > The other criterion currently written is to transcode and accept Explicit VR Little Endian otherwise (only when `--never-transcode` is not enabled).
> > (...)
> > _Originally posted by @Enet4 in [#473 (comment)](https://github.com/Enet4/dicom-rs/issues/473#issuecomment-2117643092)_
> 
> I am uncertain how to address this point and would appreciate some guidance please.

This should be already in place by the logic that follows.

In the face of uncertainty, we could begin the process of moving key components of `dicom-storescu` into a new library `dicom_storescu` and write tests for it.

**Comment by PierreBou91** [comment]
> That seems to do the trick. 👍

Ok great, thanks for the review !

> In the face of uncertainty, we could begin the process of moving key components of `dicom-storescu` into a new library `dicom_storescu` and write tests for it.

That sounds like a good idea ! I can start working on it in this PR if you agree ?

I think I will try to mimic the structure of the [dump](https://github.com/Enet4/dicom-rs/blob/master/dump/src/lib.rs) lib. If you think of other resources that might be relevant I'll gladly take a look.

I might have some questions about tests best practices later but I need to take some time to research a bit and try things by myself first. So I'll get back with a first simple commit and probably some questions as soon as I have time !

**Comment by Enet4** [comment]
Hello @PierreBou91! I don't know about the progress of the storescu lib-bin split, but given the relatively small and useful changes here that can be tested ad-hoc, it would be nice if they were made ready for review and the planned refactor deferred to a new PR.

**Comment by PierreBou91** [comment]
Hello @Enet4 ! Sorry I have not started the lib split yet, work has been a bit more intense that I was expecting lately.

You're right, I'll put this PR as ready for review and open a new one at a later date to adress the split when I have a moment !

**Review by Enet4 — APPROVED** [review]
OK, these changes provide an acceptable means of making presentation context selection deterministic: It will prefer the same transfer syntax as the file first, then (only if transcoding is supported) Explicit VR LE second, then Implicit VR LE third.

Much appreciated! :+1:

**Pull request merged**
